variables:
    PRIVATE_TOKEN: 'WARpyTCrb692GbvhmgFz'
    PLUGIN_NAME : 'languageToggleByFlag'
    RELEASE_PACKAGE_URL: '${CI_PROJECT_URL}'
    
stages:
    - release

build_plugin:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - mkdir ${PLUGIN_NAME}
        - shopt -s extglob
        - cp -r !(${PLUGIN_NAME}|.git*|.|..|tests|cypress) ${PLUGIN_NAME}
        - tar -zcvf ${PLUGIN_NAME}.tar.gz ${PLUGIN_NAME}
        - "content=$(curl --request POST --header 'Private-Token: \'${PRIVATE_TOKEN}'\' --form 'file=@./\'${PLUGIN_NAME}\'.tar.gz' 'https://gitlab.lepidus.com.br/api/v4/projects/\'${CI_PROJECT_ID}'/uploads')"
        - url_upload=$(jq -r '.url' <<<$content)
        - RELEASE_PACKAGE_URL=$RELEASE_PACKAGE_URL$url_upload
        - release-cli create --name "Release $CI_COMMIT_TAG" --description "Essa release foi gerada automaticamente. Para a instalar, use o pacote presente nos assets" --tag-name "$CI_COMMIT_TAG" --ref "$CI_COMMIT_TAG" --assets-link "{\"name\":\"${PLUGIN_NAME}.tar.gz\",\"url\":\"$RELEASE_PACKAGE_URL\"}"
